Data Preprocessing

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np
import pandas as pd
from sklearn import linear_model,metrics
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LassoCV
from sklearn.model_selection import train_test_split

In [ ]:
data=pd.read_csv('/content/drive/MyDrive/dataset/Housing.csv')

STEP ONE : Grab the dataset

In [ ]:
data.head()

Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0   1          60       RL  ...        WD         Normal    208500
1   2          20       RL  ...        WD         Normal    181500
2   3          60       RL  ...        WD         Normal    223500
3   4          70       RL  ...        WD        Abnorml    140000
4   5          60       RL  ...        WD         Normal    250000

[5 rows x 77 columns]

STEP 2 : PREPARE DATASET FOR TRAINING

Search for missing values

In [ ]:
#drop the id from the dataset
data.drop('Id',axis=1,inplace=True)

In [ ]:
data.head()

MSSubClass MSZoning  LotFrontage  ...  SaleType SaleCondition SalePrice
0          60       RL         65.0  ...        WD        Normal    208500
1          20       RL         80.0  ...        WD        Normal    181500
2          60       RL         68.0  ...        WD        Normal    223500
3          70       RL         60.0  ...        WD       Abnorml    140000
4          60       RL         84.0  ...        WD        Normal    250000

[5 rows x 76 columns]

In [ ]:
data.shape

(1460, 76)

In [ ]:
#you can use data.isna().any() to check for missing values those indicating True have missing values
data.isnull().any()

MSSubClass       False
MSZoning         False
LotFrontage       True
LotArea          False
Street           False
                 ...  
MoSold           False
YrSold           False
SaleType         False
SaleCondition    False
SalePrice        False
Length: 76, dtype: bool

In [ ]:
#get to know all columns
data.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond',
       'PavedDrive', 'WoodDeckSF'

In [ ]:
original_features=list(data.columns)
original_features
len(original_features)

76

In [ ]:
features_with_missing_values=list(data.columns[data.isna().any()])
features_with_missing_values
len(features_with_missing_values)

15

Step 3: Filling Missing Values


You can use Foward Fill : Checking for  values in previous upper cell and fill the missing cells
You can Use Backward Fill:Numbers 
Mean Fill if you have numbers
Be4 encoding you fill
Some are ordinal eg hot,cold,mild while some are nominal like gender

In [ ]:
len(data)

1460

In [ ]:
for feature in features_with_missing_values:
  print(feature,'',(data[feature].isna().sum())/len(data)*100)

LotFrontage  17.73972602739726
MasVnrType  0.547945205479452
MasVnrArea  0.547945205479452
BsmtQual  2.5342465753424657
BsmtCond  2.5342465753424657
BsmtExposure  2.6027397260273974
BsmtFinType1  2.5342465753424657
BsmtFinType2  2.6027397260273974
Electrical  0.0684931506849315
FireplaceQu  47.26027397260274
GarageType  5.5479452054794525
GarageYrBlt  5.5479452054794525
GarageFinish  5.5479452054794525
GarageQual  5.5479452054794525
GarageCond  5.5479452054794525


axis=column when you feed it with(1) when you feed it with (0) then it refers to rows

0.5 refers to 50% any thing above 50% will be dropped  since that means many fveatures are missing

In [ ]:
data.dropna(axis=1,thresh=0.5*len(data),inplace=True)

In [ ]:
data['MasVnrType']

0       BrkFace
1          None
2       BrkFace
3          None
4       BrkFace
         ...   
1455       None
1456      Stone
1457       None
1458       None
1459       None
Name: MasVnrType, Length: 1460, dtype: object

In [ ]:
mean_fill=['LotFrontage','MasVnrArea']
bfill=['FireplaceQu']
ffill=(set(features_with_missing_values)-set(mean_fill)-set(bfill))

In [ ]:
ffill

{'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'BsmtQual',
 'Electrical',
 'GarageCond',
 'GarageFinish',
 'GarageQual',
 'GarageType',
 'GarageYrBlt',
 'MasVnrType'}

In [ ]:
for feature in mean_fill:
  data[feature].fillna(data[feature].mean(),inplace=True)

In [ ]:
for feature in ffill:
  data[feature].fillna(method='ffill',inplace=True)


In [ ]:
for feature in ffill:
  data[feature].fillna(method='bfill',inplace=True)

In [ ]:
data.isna().any()

MSSubClass       False
MSZoning         False
LotFrontage      False
LotArea          False
Street           False
                 ...  
MoSold           False
YrSold           False
SaleType         False
SaleCondition    False
SalePrice        False
Length: 76, dtype: bool

# Step 3:Encode The Dataset now that we have filled all the data in the dataset

OneHotEncoding:we use nominal data
Integer Encoding: we use ordinal data

In [ ]:
cat_data=data.select_dtypes(include=['object']).copy()
cat_data.head(2)

MSZoning Street LotShape  ... PavedDrive SaleType SaleCondition
0       RL   Pave      Reg  ...          Y       WD        Normal
1       RL   Pave      Reg  ...          Y       WD        Normal

[2 rows x 39 columns]

In [ ]:
cat_features=list(cat_data.columns)
cat_features

['MSZoning',
 'Street',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'KitchenQual',
 'Functional',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'SaleType',
 'SaleCondition']

In [ ]:
nominal=['MSZoning','LandContour','LotConfig','Neighborhood']
ordinal=list(set(cat_features)-set(nominal))
numerical=list(set(original_features)-set(cat_features))
target=['SalePrice']

In [ ]:
ordinal

['Street',
 'FireplaceQu',
 'ExterCond',
 'Heating',
 'MasVnrType',
 'SaleType',
 'CentralAir',
 'Foundation',
 'RoofStyle',
 'Functional',
 'BsmtFinType2',
 'KitchenQual',
 'ExterQual',
 'Condition2',
 'SaleCondition',
 'Condition1',
 'GarageType',
 'BsmtFinType1',
 'BldgType',
 'Exterior2nd',
 'HeatingQC',
 'LandSlope',
 'PavedDrive',
 'Electrical',
 'BsmtQual',
 'HouseStyle',
 'GarageFinish',
 'BsmtExposure',
 'GarageQual',
 'GarageCond',
 'Utilities',
 'LotShape',
 'BsmtCond',
 'RoofMatl',
 'Exterior1st']

In [ ]:
data[numerical]

GarageCars  GarageArea  GarageYrBlt  ...  SalePrice  FullBath  KitchenAbvGr
0              2         548       2003.0  ...     208500         2             1
1              2         460       1976.0  ...     181500         2             1
2              2         608       2001.0  ...     223500         2             1
3              3         642       1998.0  ...     140000         1             1
4              3         836       2000.0  ...     250000         2             1
...          ...         ...          ...  ...        ...       ...           ...
1455           2         460       1999.0  ...     175000         2             1
1456           2         500       1978.0  ...     210000         2             1
1457           1         252       1941.0  ...     266500         2             1
1458           1         240       1950.0  ...     142125         1             1
1459           1         276       1965.0  ...     147500         1             1

[1460 rows x 37 columns]

In [ ]:
data[target]

SalePrice
0        208500
1        181500
2        223500
3        140000
4        250000
...         ...
1455     175000
1456     210000
1457     266500
1458     142125
1459     147500

[1460 rows x 1 columns]

In [ ]:
for feature in ordinal:
  data[feature]=(data[feature].astype('category')).cat.codes

We now encode nominal using one hot encoding

In [ ]:
df_nominal=pd.get_dummies(data[nominal])

In [ ]:
df_nominal

MSZoning_C (all)  MSZoning_FV  ...  Neighborhood_Timber  Neighborhood_Veenker
0                    0            0  ...                    0                     0
1                    0            0  ...                    0                     1
2                    0            0  ...                    0                     0
3                    0            0  ...                    0                     0
4                    0            0  ...                    0                     0
...                ...          ...  ...                  ...                   ...
1455                 0            0  ...                    0                     0
1456                 0            0  ...                    0                     0
1457                 0            0  ...                    0                     0
1458                 0            0  ...                    0                     0
1459                 0            0  ...                    0                     0

[1460 rows x 39 columns]

In [ ]:
df_numerical=data[numerical]
df_ordinal=data[ordinal]

In [ ]:
encoded_data=pd.concat([df_numerical,df_nominal,df_ordinal],axis=1)

In [ ]:
encoded_data.head(3)

GarageCars  GarageArea  GarageYrBlt  ...  BsmtCond  RoofMatl  Exterior1st
0           2         548       2003.0  ...         3         1           12
1           2         460       1976.0  ...         3         1            8
2           2         608       2001.0  ...         3         1           12

[3 rows x 111 columns]

In [ ]:
encoded_data.shape

(1460, 111)

In [ ]:
#pd.get_dummies()

# New section 
DATA NORMALIZATION (STANDARDIZATION)

In [ ]:
encoded_data[target]

SalePrice
0        208500
1        181500
2        223500
3        140000
4        250000
...         ...
1455     175000
1456     210000
1457     266500
1458     142125
1459     147500

[1460 rows x 1 columns]

In [ ]:
X=encoded_data.drop('SalePrice',axis=1)

In [ ]:
y=data[target]
y

SalePrice
0        208500
1        181500
2        223500
3        140000
4        250000
...         ...
1455     175000
1456     210000
1457     266500
1458     142125
1459     147500

[1460 rows x 1 columns]

In [ ]:
X=X.to_numpy()
X

array([[2.000e+00, 5.480e+02, 2.003e+03, ..., 3.000e+00, 1.000e+00,
        1.200e+01],
       [2.000e+00, 4.600e+02, 1.976e+03, ..., 3.000e+00, 1.000e+00,
        8.000e+00],
       [2.000e+00, 6.080e+02, 2.001e+03, ..., 3.000e+00, 1.000e+00,
        1.200e+01],
       ...,
       [1.000e+00, 2.520e+02, 1.941e+03, ..., 1.000e+00, 1.000e+00,
        5.000e+00],
       [1.000e+00, 2.400e+02, 1.950e+03, ..., 3.000e+00, 1.000e+00,
        8.000e+00],
       [1.000e+00, 2.760e+02, 1.965e+03, ..., 3.000e+00, 1.000e+00,
        6.000e+00]])

In [ ]:
y=y.to_numpy()
y

array([[208500],
       [181500],
       [223500],
       ...,
       [266500],
       [142125],
       [147500]])

In [ ]:
X.shape

(1460, 110)

In [ ]:
y.shape

(1460, 1)

In [ ]:
X=StandardScaler().fit_transform(X)
y=StandardScaler().fit_transform(y)

In [ ]:
y

array([[ 0.34727322],
       [ 0.00728832],
       [ 0.53615372],
       ...,
       [ 1.07761115],
       [-0.48852299],
       [-0.42084081]])

# PCA : PCA DIMENSIONALITY REDUCTION

In [ ]:
pca=PCA(n_components=2)
p_components=pca.fit_transform(X)

In [ ]:
p_components

array([[ 2.25226771, -1.59721881],
       [ 0.64852296,  2.56861662],
       [ 3.00109509, -0.85333788],
       ...,
       [ 1.34884237, -0.41615272],
       [-2.96150636,  2.92488205],
       [-0.89955818,  2.43106711]])

In [ ]:
#pca1 carries 10% of information about data while pca2 carries 4% of information about dataset
pca.explained_variance_ratio_

array([0.10366443, 0.04376469])

In [ ]:
#this is another way of ensuring pca capture 90% of information about dataset
pca_var=PCA(0.9)
new_pcas=pca_var.fit_transform(X)

In [ ]:
#we will train with 69 components
pca_var.n_components_

69

In [ ]:
pca_data=pd.DataFrame(p_components,columns=['PC1','PC2'])
target_data=pd.DataFrame(y,columns=['SalePrice'])
final_data=pd.concat([pca_data,target_data],axis=1)
final_data

PC1       PC2  SalePrice
0     2.252268 -1.597219   0.347273
1     0.648523  2.568617   0.007288
2     3.001095 -0.853338   0.536154
3    -1.259054  0.949494  -0.515281
4     5.492860  0.032682   0.869843
...        ...       ...        ...
1455  1.504102 -2.097391  -0.074560
1456  1.334642  3.351094   0.366161
1457  1.348842 -0.416153   1.077611
1458 -2.961506  2.924882  -0.488523
1459 -0.899558  2.431067  -0.420841

[1460 rows x 3 columns]

In [ ]:
#LassoCv.fit(xy) model will be regressor

#Using LassoCv

In [ ]:
regressor=LassoCV()

In [ ]:
regressor.fit(X,y)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:1088: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LassoCV(alphas=None, copy_X=True, cv=None, eps=0.001, fit_intercept=True,
        max_iter=1000, n_alphas=100, n_jobs=None, normalize=False,
        positive=False, precompute='auto', random_state=None,
        selection='cyclic', tol=0.0001, verbose=False)

In [ ]:
regressor.coef_

array([ 8.66290534e-02,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
       -2.18087983e-02,  3.43828419e-02,  0.00000000e+00,  4.27812969e-02,
        1.49614589e-02,  2.13230244e-03,  3.36631386e-02, -6.71654565e-02,
        1.26778641e-04,  5.63859129e-02,  4.46790686e-03, -0.00000000e+00,
        3.48795710e-02, -6.16105753e-03, -0.00000000e+00,  2.07988357e-02,
        2.87314886e-02, -0.00000000e+00,  0.00000000e+00,  2.93563285e-02,
        4.43459314e-02, -7.04979678e-03, -6.87399729e-03,  4.87471814e-02,
        1.69765042e-01, -0.00000000e+00, -0.00000000e+00,  2.67261915e-01,
        4.61622512e-02,  6.36507176e-03,  2.92002559e-02, -1.58030964e-02,
       -1.87958593e-02,  5.07257871e-03, -0.00000000e+00,  0.00000000e+00,
       -1.33586367e-03, -3.55110689e-02,  1.72022168e-02, -0.00000000e+00,
        0.00000000e+00, -0.00000000e+00,  2.07487796e-02, -1.70414338e-02,
       -1.11509539e-02,  0.00000000e+00,  0.00000000e+00, -0.00000000e+00,
        0.00000000e+00,  

In [ ]:
regressor.intercept_

2.426875504110317e-16

In [ ]:
w1=regressor.coef_[0]
w2=regressor.coef_[1]
b=regressor.intercept_


In [ ]:
X

array([[ 0.31172464,  0.35100032,  0.98587121, ...,  0.28646832,
        -0.12579688,  0.74309239],
       [ 0.31172464, -0.06073101, -0.10254651, ...,  0.28646832,
        -0.12579688, -0.5082512 ],
       [ 0.31172464,  0.63172623,  0.90524768, ...,  0.28646832,
        -0.12579688,  0.74309239],
       ...,
       [-1.02685765, -1.03391416, -1.51345838, ..., -2.71169478,
        -0.12579688, -1.44675888],
       [-1.02685765, -1.09005935, -1.15065247, ...,  0.28646832,
        -0.12579688, -0.5082512 ],
       [-1.02685765, -0.9216238 , -0.54597595, ...,  0.28646832,
        -0.12579688, -1.13392299]])

In [ ]:
y

array([[ 0.34727322],
       [ 0.00728832],
       [ 0.53615372],
       ...,
       [ 1.07761115],
       [-0.48852299],
       [-0.42084081]])

# New Section Data Splitting

In [ ]:
X=pca_data
y=target_data

In [ ]:
#X_train,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=101)
X_train,X_test,y_train,y_test=train_test_split(X, y, train_size=0.3,test_size=0.3, random_state=101)
y_train

SalePrice
1312   1.524628
1408  -0.697866
1165   0.657919
1346   1.027243
399    0.756514
...         ...
702    2.279130
572    0.548746
1192  -0.704162
206   -0.466172
818   -0.326401

[438 rows x 1 columns]

# Model Selection

In [ ]:

result={}
models={
   'LinearRegression': linear_model.LinearRegression(),
    'Laso':linear_model.Lasso(),
    'Ridge':linear_model.Ridge(),
    'ElasticNet':linear_model.ElasticNet()
}
#modelli=linear_model.LinearRegression()
#modelli.fit(X_train,y_train)
#modelli.fit(X,y)
#accuracy=modelli.score(X_test,y_test)

for i in models:
  models[i].fit(X_train,y_train)
  accuracy=models[i].score(X_test,y_test)
  result[i]=[accuracy]
  pd.DataFrame(result)

In [ ]:
pd.DataFrame(result)

LinearRegression      Laso     Ridge  ElasticNet
0          0.676927  0.611589  0.676945    0.657662

In [ ]:
target_data

SalePrice
0      0.347273
1      0.007288
2      0.536154
3     -0.515281
4      0.869843
...         ...
1455  -0.074560
1456   0.366161
1457   1.077611
1458  -0.488523
1459  -0.420841

[1460 rows x 1 columns]

In [ ]:
pca_data

PC1       PC2
0     2.252268 -1.597219
1     0.648523  2.568617
2     3.001095 -0.853338
3    -1.259054  0.949494
4     5.492860  0.032682
...        ...       ...
1455  1.504102 -2.097391
1456  1.334642  3.351094
1457  1.348842 -0.416153
1458 -2.961506  2.924882
1459 -0.899558  2.431067

[1460 rows x 2 columns]

In [ ]:
X

PC1       PC2
0     2.252268 -1.597219
1     0.648523  2.568617
2     3.001095 -0.853338
3    -1.259054  0.949494
4     5.492860  0.032682
...        ...       ...
1455  1.504102 -2.097391
1456  1.334642  3.351094
1457  1.348842 -0.416153
1458 -2.961506  2.924882
1459 -0.899558  2.431067

[1460 rows x 2 columns]